project:
  type: book

book:
  title: "Eksamen IDR4000"
  author: "Kandidatnummer 104"
  date: "2022-12-02"
  chapters:
    - index.qmd
    - part1.qmd
    - part2.qmd
    - part3.qmd
    - part4.qmd
    - part5.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

crossref: 
  fig-labels: arabic
  fig-title: "Figur"
  tbl-labels: arabic
  tbl-title: "Tabell"

format:
  pdf:
    documentclass: scrreprt
    number-sections: false
    linestretch: 1.5
    mainfont: "Times New Roman"
    fontsize: 12p



