# Deloppgave 4: Studiedesign

## Introduskjon til tema

Jeg har valgt å sammenligne studier som undersøker effekten av detrening på utholdenhetsvariabler. Utholdenhetstrening fører til adaptasjoner som forbedrer kroppens evne til å transportere oksygen til arbeidene muskelceller og forbruke oksygen til ATP-syntese i arbeidene muskelceller [@tonnessen_trening_2018]. Når vi slutter å stimulere kroppen med trening, får vi etter hvert en reduksjon i de oppnådde treningsadaptasjonene [@tonnessen_trening_2018]. Kunnskap om fysiologiske og molekylære mekanismer i sammenheng med detrening er dermed av interesse. I tillegg vil kartlegging av hastighet og omfang av reduksjon i fysiologisk funksjon som følge av detrening belyse viktigheten av vedlikeholdstrening i et prestasjons- og helseperspektiv. Det har blitt observert reduksjoner i VO~2maks~ etter 2-3 uker med detrening hos utholdenhetstrente personer [@houston_interrelationships_1979; @coyle_time_1984; @coyle_effects_1986; @chen_two_2022]. Den akutte reduksjonen i VO~2maks~ ser ut til å skyldes en reduksjon i hjertets slagvolum (SV) på grunn av redusert blodvolum (BV) [@coyle_effects_1986]. Utholdenhetsvariabler i trente muskelceller ser også ut til å få en rask akutt reduksjon som følge av detrening. Etter 1-2 uker med detrening er det observert en redusert mengde aerobe enzymer [@houston_interrelationships_1979] og over 1-2 år er det observert endringer i fibertypesammensetning [@larsson_effects_1985].

\newpage

## Metodelogisk sammenligning av studier

Av artikklene jeg trekker frem er @larsson_effects_1985 den eneste observasjonsstudien. Den har blitt gjennomført som en prospektiv kohorte-studie [@browner_designing_2023] som følger satsingen til 11 svenske elite-roere i en fire års periode mot OL i 1980. Målet med studien var å studere effekten av mange år med systematisk trening og detrening på histokjemiske og funksjonelle egenskaper i skelettmuskulatur. De fire gjenværende studiene er alle intervensjonsstudier med "case-crossover" design av kortere varighet [@browner_designing_2023]. Case-crossover studier er en type retrospektiv studie som bruker en gruppe personer som alle har en ønsket egenskap (godt utviklet utholdenhetsegenskaper) for så å gjøre en intervensjon (detrening) må påfølgende målinger av egenskapen, dermed fungerer gruppen som sin egen kontrollgruppe [@browner_designing_2023]. @houston_interrelationships_1979 undersøkte effekten av 15 dager med detrening og 15 dager med retrening på VO~2maks~, løpsprestasjon og mengde aerobe enzymer for 6 godt trente løpere. @chen_two_2022 undersøkte effekten av 2 uker med detrening på VO~2maks~, muskelstyrke og muskulær utholdenhet i 15 utholdenhetstrente utøvere, i tillegg til effekten av muskelstyrke på kardiovaskulær funksjon under detrening. @coyle_time_1984 hadde en litt annen vinkling, de hadde som mål å få info om hvor raskt og fullstendig adaptasjonene til 7 utholdenhetstrente personer forsvinner ved detrening. De observerte dermed effekten av detrening på utholdenhetsvariabler i inntil 84 dager med detrening. @coyle_effects_1986 undersøker om nedgangen i SV som følge av 2-4 uker med detrening i 8 utholdenhetstrente utøvere er assosiert med redusert BV, og om kardiovaskulær funksjon kan gjenskapes med klinisk ekspansasjon av BV til utgangsnivået. Alle de respektive studiene har undersøkt effekten av detrening på allerede utholdenhetstrente utøvere som er en fordel iht oppdagelse av reduksjon i adaptasjoner. Alle studiene oppgir dermed også antall treningsår før detreningsperioden starter og treningsstatus på utøverne, f.eks. VO~2maks~ ved pretest. 

Av deltakerene i @larsson_effects_1985 økte syv stykker det fysiske treningsnivået gjennom perioden, mens fire sluttet med aktiv roing 1-2 år før OL. Treningsdata ble samlet inn via intervjue av deltakerne. @larsson_effects_1985 undersøkte dermed effekten av detrening på utvikling av utholdenhetsvariabler i starten-, underveis og etter perioden ved å sammenligne deltakerne som trente roing gjennom hele perioden med deltakerne som sluttet med roing i løpet av perioden. Biopsier ble tatt fra vastus lateralis og den dorsale delen av deltoid muskelen 2-3 ganger i løpet av fire års perioden og VO~2maks~ og styrke ble målt to ganger årlig. Biopsier ble ikke tatt i samme muskelgruppe i alle studiene, til motsetning fra @larsson_effects_1985 ble det tatt biopsi i gastrocnemius på løperne i @houston_interrelationships_1979 og enten gastrocnemius eller vastus lateralis i @coyle_time_1984 for løpere og syklister respektivt. Man må dermed være forsiktig med sammenligninger av fibertypesammensetning og fiberareal på tvers av muskelgrupper da det kan være store forskjeller. Felles for studiene er at biopsiene ble tatt i muskelgrupper som er svært aktive i bevegelsesformen som utøverne gjennomførte. En svakhet i @larsson_effects_1985 er at deltakerne som betraktes som detreningsgruppen ikke var fullstendig treningsfri, de fortsatte med lette jogge- og roøkter i tillegg til normale hverdagslige aktiviteter. Under detreningsperioden i @houston_interrelationships_1979 fikk deltakerne et "gåplaster" som immobiliserte soleus muskelen i leggen, i de syv første dagene av detreningsperioden. De resterende dagene ble deltakerne bedt om å frastå all fysisk anstrengende aktivitet. I @coyle_time_1984, @coyle_effects_1986 og @chen_two_2022 ble deltakerne bedt om å frastå fra all fysisk trening, men leve et normalt hverdagslig liv. Ingen av studiene har forsøkt å måle fysisk aktivitet underveis i detreningsperioden. Det kan tenkes at de personene som hadde høyest aktivitetsnivå under detreningsperioden også vedlikeholdt fysiologisk funkjson best. 

For å teste effekten av detrening på utholdenhetsvariabler brukte @chen_two_2022 og @houston_interrelationships_1979 tohalet paired t-test med utvikling i respektive utholdenhetsvariabler som avhengig variabel og pre- og posttest som uavhengig variabel. De fant en negativ effekt av detrening på VO~2maks~, SV~maks~ og styrke i isokenetisk kneekstensjon, men ikke muskulær utholdenhet. @larsson_effects_1985 undersøkte effekten av detrening på utholdenhetsvariabler over de ulike tidspunkten med en uavhengig t-test mellom gruppen som trente i 4 år og gruppen som trente i 2-3 år. På slutten av observasjonsperioden fant de forskjeller i muskelegenskaper mellom aktive roere og detrente roere på grunn av negative endringer i detrente roere. I @coyle_time_1984 ble en repeterte målinger ANOVA test brukt for å undersøke effekten av detrening over flere tidspunkt (12, 21, 56 og 84) og Tuckey's post hoc test for å identifisere hvilke tidspunkt som skilte seg fra hverandre, samt uavhengig t-test mellom detreningsgruppen og kontrollgruppen, dette er den eneste studien som har med en kontrollgruppe. De så en negativ effekt av detrening på VO~2maks~, SV, a-vO~2~ differanse og mitokondrie volum. @coyle_effects_1986 testet effekten av både detrening og blodplasma ekspansasjon på utviklingsvariabler fra pre- til posttest med en tosidet repeterte målinger ANOVA med Tuckey's post hoc tester for å identifisere signifikante forskjeller. De fant også en negativ effekt av detrening på VO~2maks~ og SV. Ingen av studiene oppgir at de på forhånd har kalkulert utvalgstørrelsen basert på statistisk styrke.  

En effekt av detrening på utholdenhetsvariabler ble funnet i alle studiene [@houston_interrelationships_1979; @coyle_time_1984; @coyle_effects_1986; @chen_two_2022; @larsson_effects_1985], til tross for at utvalgstørrelsen var lav i alle studiene. Dette tyder på at effekten av detrening på utholdenhetsvariabler er såpass stor at en stor utvalgsstørrelse ikke er nødvendig for å fange opp effekten.  

## Konklusjon

Fremtidige studier som vil undersøke lignende spørsmål/hypoteser bør inkludere kvinner for å undersøke om effektene ser like ut for begge kjønn. Kontrollgrupper burde benyttes og statistisk styrke bør kalkuleres før start. Mål på fysisk aktivitet under detreningsperioden vil kunne sikre at deltakerne følger prosjektets intensjon. Bedre forståelse for fysiologiske og molekylære mekanismer burde etterstrebes, særlig tilpasninger i genutrykk og proteinaktivitet. 
